This is my first book

In [9]:
import numpy as np

In [12]:
array = np.array([1,2,3,4])
lst = [1,2,3,4]
tup = (1,2,3,4)
print(lst)
print(array)
print(tup)
type(array), type(lst)

[1, 2, 3, 4]
[1 2 3 4]


(numpy.ndarray, list)

Create an array of zeros in the size of the first argument

In [14]:
zeros = np.zeros(10, dtype = int)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
lst_zeros = [0] * 1_000_000

In [17]:
import time

# Record the start time
start_time = time.perf_counter()

# --- Code you want to measure goes here ---
# Example: a time-consuming loop or function call
for i in range(1_000_000):
    lst_zeros[i] += 1
# -----------------------------------------

# Record the end time
end_time = time.perf_counter()

# Calculate the elapsed duration in seconds (as a float)
elapsed_seconds = end_time - start_time
elapsed_seconds

0.09919585599982383

EX1:
Write a python function, named time_to_array_addition the function gets as input an array or a list. Check the type and adds 1 to each argument in the array list and prints the time it took.

In [34]:
def time_to_array_addition(a):
  type(a)
  for i in range(len(a)):
    a[i] += 1

start_time = time.perf_counter()

a = np.array([1,2,3,4,5])

#a = [1,2,3,4,5]

time_to_array_addition(a)

end_time = time.perf_counter()

elapsed_time = end_time - start_time

print(elapsed_time)
print(a)

0.000315332999889506
[2 3 4 5 6]


#EX2:
write a function named ex2 that takes an array finds it's maximum value and than create a new array from zero to maximum value in steps of 3


In [50]:
def ex2(array):
  max_num = max(array)
  new_array = np.arange(0,max_num+1,3)
  return new_array

print(ex2(np.array([1,2,6,9,15])))


[ 0  3  6  9 12 15]


In [55]:
new_array = np.arange(1,6)
new_array.max()
new_array.min()

np.int64(1)

In [58]:
two_d = np.array([[1,2,3], ['a', 'b', 'c']])
print(two_d.shape)
type(two_d[0])

(2, 3)


numpy.ndarray

In [59]:
import pandas as pd

In [60]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("heptapod/titanic")

print("Path to dataset files:", path)


Using Colab cache for faster access to the 'titanic' dataset.
Path to dataset files: /kaggle/input/titanic


In [63]:
df = pd.read_csv("/kaggle/input/titanic/train_and_test2.csv")

In [64]:
df

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0   
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0   
1          0  ...        0        0        0       1        0        0   
2          0  ...        0        0        0       3        0        0   
3          0  ...        0        0        0       1        0        0   
4          0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
0          2.0        0        0         0  
1          0.0        0        0         1  
2          2.0        0        0         1  
3          2.0        0        0         1  
4          2.0        0        0         0  
...        ...      ...      ...       ...  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[1309 rows x 28 columns]

In [70]:
df_small = df[["Passengerid", "2urvived", "Age"]]

In [71]:
df_small

Passengerid  2urvived   Age
0               1         0  22.0
1               2         1  38.0
2               3         1  26.0
3               4         1  35.0
4               5         0  35.0
...           ...       ...   ...
1304         1305         0  28.0
1305         1306         0  39.0
1306         1307         0  38.5
1307         1308         0  28.0
1308         1309         0  28.0

[1309 rows x 3 columns]

EX3:
load the titanic dataset, calculate the correlations, and print the correlation between the passengerid and 2urvived

In [87]:
df_small.corr()

Passengerid  2urvived       Age
Passengerid     1.000000 -0.331493  0.025799
2urvived       -0.331493  1.000000 -0.055862
Age             0.025799 -0.055862  1.000000

In [82]:
print(f"the correlation between Passengerid and 2survived is {df_small['Passengerid'].corr(df_small['2urvived'])}")

the correlation between Passengerid and 2survived is -0.33149303092420623


In [88]:
corr = df_small.corr()
res = corr['Passengerid'].iloc[1]
print(res)

-0.331493030924206


In [89]:
df

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0   
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0   
1          0  ...        0        0        0       1        0        0   
2          0  ...        0        0        0       3        0        0   
3          0  ...        0        0        0       1        0        0   
4          0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
0          2.0        0        0         0  
1          0.0        0        0         1  
2          2.0        0        0         1  
3          2.0        0        0         1  
4          2.0        0        0         0  
...        ...      ...      ...       ...  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[1309 rows x 28 columns]

In [90]:
df_small

Passengerid  2urvived   Age
0               1         0  22.0
1               2         1  38.0
2               3         1  26.0
3               4         1  35.0
4               5         0  35.0
...           ...       ...   ...
1304         1305         0  28.0
1305         1306         0  39.0
1306         1307         0  38.5
1307         1308         0  28.0
1308         1309         0  28.0

[1309 rows x 3 columns]

In [91]:
df = df[["Passengerid", "Age",	"Fare",	"Sex",	"sibsp", "2urvived"]]

In [92]:
df

Passengerid   Age      Fare  Sex  sibsp  2urvived
0               1  22.0    7.2500    0      1         0
1               2  38.0   71.2833    1      1         1
2               3  26.0    7.9250    1      0         1
3               4  35.0   53.1000    1      1         1
4               5  35.0    8.0500    0      0         0
...           ...   ...       ...  ...    ...       ...
1304         1305  28.0    8.0500    0      0         0
1305         1306  39.0  108.9000    1      0         0
1306         1307  38.5    7.2500    0      0         0
1307         1308  28.0    8.0500    0      0         0
1308         1309  28.0   22.3583    0      1         0

[1309 rows x 6 columns]

In [96]:
df_new = df.rename(columns={"2urvived":"survived"})

In [97]:
df_new

Passengerid   Age      Fare  Sex  sibsp  survived
0               1  22.0    7.2500    0      1         0
1               2  38.0   71.2833    1      1         1
2               3  26.0    7.9250    1      0         1
3               4  35.0   53.1000    1      1         1
4               5  35.0    8.0500    0      0         0
...           ...   ...       ...  ...    ...       ...
1304         1305  28.0    8.0500    0      0         0
1305         1306  39.0  108.9000    1      0         0
1306         1307  38.5    7.2500    0      0         0
1307         1308  28.0    8.0500    0      0         0
1308         1309  28.0   22.3583    0      1         0

[1309 rows x 6 columns]

EX4
Check the correlation between the Fare and the Pclass, and the correlation between survived and Sex. Finally print which is higher



In [115]:
corr = df_new.corr()
corr
corr1 = corr['Fare'].iloc[3]
corr2 = corr['survived'].iloc[4]
max_corr = max(corr1,corr2)
print(f"The correlation between fare and sex is {corr1}, the correlation between survived and sibsp is{corr2} and the feature with the higher correlations are: {max_corr}")

The correlation between fare and sex is 0.18568128646707774, the correlation between survived and sibsp is-0.014375452914690567 and the feature with the higher correlations are: 0.18568128646707774


In [118]:
corr = df_new.corr()
corr1 = corr['Fare']['Sex']
corr2 = corr['survived']['sibsp']
max_corr = max(corr1,corr2)
print(f"The correlation between fare and sex is {corr1}, the correlation between survived and sibsp is{corr2} and the feature with the higher correlations are: {max_corr}")

The correlation between fare and sex is 0.18568128646707774, the correlation between survived and sibsp is-0.014375452914690567 and the feature with the higher correlations are: 0.18568128646707774
