# This is my first notebook

Here we are going to show basic function [facebook](https://facebook.com)
print("THIS IS PYTHON")

In [ ]:
print("This is print")

"This won't be printed"

"This is output"

This is print


'This is output'

In [ ]:
import numpy as np

In [ ]:
array = np.array([1, -1, 3, 4], dtype=bool)
lst = [1, 2, 3, 4]
tup = (1, 2, 3, 4)
print(array)
type(array), type(lst)

[ True  True  True  True]


(numpy.ndarray, list)

In [ ]:
tup[0] = -1

NameError: name 'tup' is not defined

creates an array of zeros in the size of the first argument

In [ ]:
zeros = np.zeros(1_000_000, dtype=int)

zeros


This is print


'This is output'

In [ ]:
lst_zeros = [0] * 1_000_000
lst_zeros

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [ ]:
import time

# Record the start time
start_time = time.perf_counter()

# --- Code you want to measure goes here ---
# Example: a time-consuming loop or function call
for i in range(1_000_000):
    lst_zeros[i] += 1
# -----------------------------------------

# Record the end time
end_time = time.perf_counter()

# Calculate the elapsed duration in seconds (as a float)
elapsed_seconds = end_time - start_time
elapsed_seconds

0.1942135330000383

# EX1:
Write a python function, named time_to_array_addition
the function gets as input an array or a list. Check the type and adds 1 to each argument in the array or list and prints the time it took.

In [ ]:
def time_to_array_addition(a):
  """
  This function tests if a is a numpy array or list
  """
  start_time = time.perf_counter()
  if type(a) == type([]): # a is list
    for i in range(len(a)):
      a[i] += 1
  elif type(a) == type(np.array([0])): # a is a numpy array
      a += 1
  else: # a is nither
    print('error')

  end_time = time.perf_counter()
  print(f"Time taken: {end_time - start_time}")
  return a

In [ ]:
type(lst_zeros) == type([1, 2, 3])
isinstance([1, 2, 3], int)

False

In [ ]:
time_to_array_addition(lst_zeros)
time_to_array_addition(zeros)

Time taken: 0.061960866999470454
Time taken: 0.002463870999235951


array([5., 5., 5., ..., 5., 5., 5.])

In [ ]:
zeros = np.zeros(1_000_000)
ones = zeros + 1
zeros

array([0., 0., 0., ..., 0., 0., 0.])

%time

In [ ]:
%time

zeros += 1

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.2 µs


In [ ]:
%time
for i in range(len(lst_zeros)):
  lst_zeros[i] += 1

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.01 µs


%who

In [ ]:
%who

Math	 array	 elapsed_seconds	 end_time	 i	 lst	 lst_zeros	 math	 np	 
numpy	 ones	 start_time	 time	 time_to_array_addition	 tup	 zeros	 


In [ ]:
new_x = 10

In [ ]:
%who

Math	 array	 elapsed_seconds	 end_time	 i	 lst	 lst_zeros	 math	 new_x	 
np	 numpy	 ones	 start_time	 time	 time_to_array_addition	 tup	 zeros	 


In [ ]:
del new_x

In [ ]:
%who

Math	 array	 elapsed_seconds	 end_time	 i	 lst	 lst_zeros	 math	 np	 
numpy	 ones	 start_time	 time	 time_to_array_addition	 tup	 zeros	 


np.arange

In [ ]:
np.arange(10, 2)

array([], dtype=int64)

#EX2:
write a function named ex2 that takes an array finds it's maximum value and than create a new array from zero to maximum value in steps of 3

In [ ]:
max(np.arange(start=10, stop=2, step=-1))
res = np.arange(start=10, stop=2, step=-1).max()
type(res)

numpy.int64

In [ ]:
2**16-1

65535

shape

In [ ]:
new_array = np.arange(1, 6)
new_array.max()
new_array.min()

new_array

array([1, 2, 3, 4, 5])

In [ ]:
new_array.shape

(5,)

In [ ]:
# two_d = np.array([[1,2,3], ['a', 'b', 'c', 'd']])
two_d = np.array([[1, 2, 3], ['a', 'b', 'c']]) # [1, 2, 3, 'a', 'b', 'c'] This is saved like this
print(two_d.shape)
two_d

(2, 3)


array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U21')

In [ ]:
lst = [[1,2,3], ['a', 'b', 'c', 'd']]
lst

[[1, 2, 3], ['a', 'b', 'c', 'd']]

In [ ]:
example = np.array([[14, 20]])
# example = np.array([14])#, 20])
example[0] # scalar
example[0:].shape
# example[0:].max()
# example[0:].min()


(1, 2)

In [ ]:
type(two_d[0])

numpy.ndarray

Pandas

In [ ]:
import pandas as pd

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("heptapod/titanic")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'titanic' dataset.
Path to dataset files: /kaggle/input/titanic


In [ ]:
!pwd

/content


In [ ]:
df = pd.read_csv("/kaggle/input/titanic/train_and_test2.csv")

In [ ]:
df.head(10)

Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0            1  22.0   7.2500    0      1     0       0       0       0   
1            2  38.0  71.2833    1      1     0       0       0       0   
2            3  26.0   7.9250    1      0     0       0       0       0   
3            4  35.0  53.1000    1      1     0       0       0       0   
4            5  35.0   8.0500    0      0     0       0       0       0   
5            6  28.0   8.4583    0      0     0       0       0       0   
6            7  54.0  51.8625    0      0     0       0       0       0   
7            8   2.0  21.0750    0      3     0       0       0       0   
8            9  27.0  11.1333    1      0     0       0       0       0   
9           10  14.0  30.0708    1      1     0       0       0       0   

   zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  Embarked  \
0       0  ...        0        0        0       3        0        0       2.0   
1       0  ...        0        0        0       1        0        0       0.0   
2       0  ...        0        0        0       3        0        0       2.0   
3       0  ...        0        0        0       1        0        0       2.0   
4       0  ...        0        0        0       3        0        0       2.0   
5       0  ...        0        0        0       3        0        0       1.0   
6       0  ...        0        0        0       1        0        0       2.0   
7       0  ...        0        0        0       3        0        0       2.0   
8       0  ...        0        0        0       3        0        0       2.0   
9       0  ...        0        0        0       2        0        0       0.0   

   zero.17  zero.18  2urvived  
0        0        0         0  
1        0        0         1  
2        0        0         1  
3        0        0         1  
4        0        0         0  
5        0        0         0  
6        0        0         0  
7        0        0         0  
8        0        0         1  
9        0        0         1  

[10 rows x 28 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1309 non-null   int64  
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64  
 4   sibsp        1309 non-null   int64  
 5   zero         1309 non-null   int64  
 6   zero.1       1309 non-null   int64  
 7   zero.2       1309 non-null   int64  
 8   zero.3       1309 non-null   int64  
 9   zero.4       1309 non-null   int64  
 10  zero.5       1309 non-null   int64  
 11  zero.6       1309 non-null   int64  
 12  Parch        1309 non-null   int64  
 13  zero.7       1309 non-null   int64  
 14  zero.8       1309 non-null   int64  
 15  zero.9       1309 non-null   int64  
 16  zero.10      1309 non-null   int64  
 17  zero.11      1309 non-null   int64  
 18  zero.12      1309 non-null   int64  
 19  zero.1

In [ ]:
df.isna().sum()

Passengerid    0
Age            0
Fare           0
Sex            0
sibsp          0
zero           0
zero.1         0
zero.2         0
zero.3         0
zero.4         0
zero.5         0
zero.6         0
Parch          0
zero.7         0
zero.8         0
zero.9         0
zero.10        0
zero.11        0
zero.12        0
zero.13        0
zero.14        0
Pclass         0
zero.15        0
zero.16        0
Embarked       2
zero.17        0
zero.18        0
2urvived       0
dtype: int64

In [ ]:
age_column = df["Age"]
age_column

0       22.0
1       38.0
2       26.0
3       35.0
4       35.0
        ... 
1304    28.0
1305    39.0
1306    38.5
1307    28.0
1308    28.0
Name: Age, Length: 1309, dtype: float64

In [ ]:
# df_small = df[["Passengerid", "Age", "2urvived"]]
df_small = df[["Passengerid", "Age", '2urvived']]
df_small

Passengerid   Age  2urvived
0               1  22.0         0
1               2  38.0         1
2               3  26.0         1
3               4  35.0         1
4               5  35.0         0
...           ...   ...       ...
1304         1305  28.0         0
1305         1306  39.0         0
1306         1307  38.5         0
1307         1308  28.0         0
1308         1309  28.0         0

[1309 rows x 3 columns]

In [ ]:
df.columns

Index(['Passengerid', 'Age', 'Fare', 'Sex', 'sibsp', 'zero', 'zero.1',
       'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6', 'Parch', 'zero.7',
       'zero.8', 'zero.9', 'zero.10', 'zero.11', 'zero.12', 'zero.13',
       'zero.14', 'Pclass', 'zero.15', 'zero.16', 'Embarked', 'zero.17',
       'zero.18', '2urvived'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=1309, step=1)

In [ ]:
df_small.corr()

Passengerid       Age  2urvived
Passengerid     1.000000  0.025799 -0.331493
Age             0.025799  1.000000 -0.055862
2urvived       -0.331493 -0.055862  1.000000

# What is correlation:
  * [in short](https://https://www.youtube.com/shorts/x7DTp4ZpAWw)
  * [longer explanation with an example](https://www.youtube.com/watch?v=dsyTQNUvqH0&t=12s)

# EX3:
load the titanic dataset, calculate the correlations, and print the correlation between the passengerid and 2urvived

In [ ]:
corr = df_small.corr()
res = corr['Passengerid'].iloc[2]

In [ ]:
print(f"The correlation between passengerid and 2urvived: {res}")

The correlation between passengerid and 2urvived: -0.331493030924206


In [ ]:
corr.iloc[0, 0] # Works by index like indixing in lists/arrays
corr.loc["Passengerid", "Age"] # works based on columns and rows names

np.float64(0.025798517148073012)

In [ ]:
df.columns

Index(['Passengerid', 'Age', 'Fare', 'Sex', 'sibsp', 'zero', 'zero.1',
       'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6', 'Parch', 'zero.7',
       'zero.8', 'zero.9', 'zero.10', 'zero.11', 'zero.12', 'zero.13',
       'zero.14', 'Pclass', 'zero.15', 'zero.16', 'Embarked', 'zero.17',
       'zero.18', '2urvived'],
      dtype='object')

In [ ]:
df = df[["Passengerid", 'Age', 'Fare', 'Sex', 'sibsp', 'Pclass', '2urvived']] # this will override the df variable

In [ ]:
df_new = df.rename(columns={"2urvived": "Survived"}) # Renames the columns from key to value
df_new.head()

Passengerid   Age     Fare  Sex  sibsp  Pclass  Survived
0            1  22.0   7.2500    0      1       3         0
1            2  38.0  71.2833    1      1       1         1
2            3  26.0   7.9250    1      0       3         1
3            4  35.0  53.1000    1      1       1         1
4            5  35.0   8.0500    0      0       3         0

# EX4
Check the correlation between the Fare and the Pclass, and the correlation between survived and Sex. Finally print which is higher

In [ ]:
df_new.corr()['Passengerid']

Passengerid    1.000000
Age            0.025799
Fare           0.031128
Sex           -0.013406
sibsp         -0.055224
Pclass        -0.038354
Survived      -0.331493
Name: Passengerid, dtype: float64

In [ ]:
df_new.corr()['Sex']['Survived']

np.float64(0.4040200356653614)

In [ ]:
corr_Fare_Pclass = df_new.corr()["Fare"].iloc[-2]
corr_sex_survived = df_new.corr()['Sex']['Survived']
corr_higher =

print(f"The correlation between fare and pclass is {}, the correlation between sex and survived is{} and the features with the higher correlations are: {}")

# Homework

In this home work you are going to work and learn about numpy and pandas.
If you are met with a function you are not familair with you are expected to search and learn about it your self! Don't worry the internet is full of explanations and tutorials about this packages and you can do it!

## Numpy
Make sure you are testing everything

1. Write a function that gets an argument n, checks if it's higher than 0 and than generates an array in that size of ones.


2. Write a function that gets an argument n, checks if it's higher than 0 and than generates an array in that size between 0 to n with step 2.

3. Write a python function that takes to arrays and calculates their correaltion
hint: Numpy already implemented everything!

4. Write a python function that takes two arrays and checks if all the elements are equal



5. Write a python function that takes two arrays and checks if they contain the same variables not neccesserly in the same order