This is my first book

In [62]:
import numpy as np

In [63]:
array = np.array([1,2,3,4])
lst = [1,2,3,4]
tup = (1,2,3,4)
print(lst)
print(array)
print(tup)
type(array), type(lst)

[1, 2, 3, 4]
[1 2 3 4]
(1, 2, 3, 4)


(numpy.ndarray, list)

Create an array of zeros in the size of the first argument

In [64]:
zeros = np.zeros(10, dtype = int)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [65]:
lst_zeros = [0] * 1_000_000

In [66]:
import time

# Record the start time
start_time = time.perf_counter()

# --- Code you want to measure goes here ---
# Example: a time-consuming loop or function call
for i in range(1_000_000):
    lst_zeros[i] += 1
# -----------------------------------------

# Record the end time
end_time = time.perf_counter()

# Calculate the elapsed duration in seconds (as a float)
elapsed_seconds = end_time - start_time
elapsed_seconds

0.12091496400000779

EX1:
Write a python function, named time_to_array_addition the function gets as input an array or a list. Check the type and adds 1 to each argument in the array list and prints the time it took.

In [67]:
def time_to_array_addition(a):
  type(a)
  for i in range(len(a)):
    a[i] += 1

start_time = time.perf_counter()

a = np.array([1,2,3,4,5])

#a = [1,2,3,4,5]

time_to_array_addition(a)

end_time = time.perf_counter()

elapsed_time = end_time - start_time

print(elapsed_time)
print(a)

0.00023120100001960964
[2 3 4 5 6]


In [68]:
# Yuval code:

# def time_to_array_addition(a):
#   """
#   This function tests if a is a numpy array or list
#   """
#   start_time = time.perf_counter()
#   if type(a) == type([]): # a is list
#     for i in range(len(a)):
#       a[i] += 1
#   elif type(a) == type(np.array([0])): # a is a numpy array
#       a += 1
#   else: # a is nither
#     print('error')

#   end_time = time.perf_counter()

#   print(f"Time taken: {end_time - start_time}")
#   return a


In [69]:
type(lst_zeros) == type([1, 2, 3])
isinstance([1, 2, 3], list)

True

In [70]:
zeros = np.zeros(1_000_000)
ones = zeros + 1
zeros
ones

array([1., 1., 1., ..., 1., 1., 1.])

In [71]:
%time

zeros += 1

CPU times: user 15 µs, sys: 2 µs, total: 17 µs
Wall time: 21.2 µs


In [72]:
%who

a	 age_column	 array	 b	 check_if_equal	 contain_same_variables	 corr	 corr1	 corr2	 
correlation_two_arrays	 df	 df_new	 df_small	 elapsed_seconds	 elapsed_time	 end_time	 ex2	 higher_than_0	 
i	 kagglehub	 lst	 lst_zeros	 max_corr	 max_values	 new_array	 np	 ones	 
path	 pd	 res	 start_time	 time	 time_to_array_addition	 tup	 two_d	 zeros	 



In [73]:
new_x = 10

In [74]:
%who

a	 age_column	 array	 b	 check_if_equal	 contain_same_variables	 corr	 corr1	 corr2	 
correlation_two_arrays	 df	 df_new	 df_small	 elapsed_seconds	 elapsed_time	 end_time	 ex2	 higher_than_0	 
i	 kagglehub	 lst	 lst_zeros	 max_corr	 max_values	 new_array	 new_x	 np	 
ones	 path	 pd	 res	 start_time	 time	 time_to_array_addition	 tup	 two_d	 
zeros	 


In [75]:
del new_x

In [76]:
%who

a	 age_column	 array	 b	 check_if_equal	 contain_same_variables	 corr	 corr1	 corr2	 
correlation_two_arrays	 df	 df_new	 df_small	 elapsed_seconds	 elapsed_time	 end_time	 ex2	 higher_than_0	 
i	 kagglehub	 lst	 lst_zeros	 max_corr	 max_values	 new_array	 np	 ones	 
path	 pd	 res	 start_time	 time	 time_to_array_addition	 tup	 two_d	 zeros	 



In [77]:
new_array = np.arange(2,10)
print(new_array)

[2 3 4 5 6 7 8 9]


#EX2:
write a function named ex2 that takes an array finds it's maximum value and than create a new array from zero to maximum value in steps of 3


In [78]:
def ex2(array):
  max_num = max(array)
  new_array = np.arange(0,max_num+1,3)
  return new_array

print(ex2(np.array([1,2,6,9,15])))


[ 0  3  6  9 12 15]


In [79]:
new_array = np.arange(1,6)
new_array.max()
new_array.min()

np.int64(1)

In [80]:
two_d = np.array([[1,2,3], ['a', 'b', 'c']])
print(two_d.shape)
type(two_d[0])

(2, 3)


numpy.ndarray

Pandas

In [81]:
import pandas as pd

In [82]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("heptapod/titanic")

print("Path to dataset files:", path)


Using Colab cache for faster access to the 'titanic' dataset.
Path to dataset files: /kaggle/input/titanic


In [83]:
!pwd

/content


In [84]:
df = pd.read_csv("/kaggle/input/titanic/train_and_test2.csv")

In [85]:
df

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0   
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0   
1          0  ...        0        0        0       1        0        0   
2          0  ...        0        0        0       3        0        0   
3          0  ...        0        0        0       1        0        0   
4          0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
0          2.0        0        0         0  
1          0.0        0        0         1  
2          2.0        0        0         1  
3          2.0        0        0         1  
4          2.0        0        0         0  
...        ...      ...      ...       ...  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[1309 rows x 28 columns]

In [86]:
df.head(10)

Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0            1  22.0   7.2500    0      1     0       0       0       0   
1            2  38.0  71.2833    1      1     0       0       0       0   
2            3  26.0   7.9250    1      0     0       0       0       0   
3            4  35.0  53.1000    1      1     0       0       0       0   
4            5  35.0   8.0500    0      0     0       0       0       0   
5            6  28.0   8.4583    0      0     0       0       0       0   
6            7  54.0  51.8625    0      0     0       0       0       0   
7            8   2.0  21.0750    0      3     0       0       0       0   
8            9  27.0  11.1333    1      0     0       0       0       0   
9           10  14.0  30.0708    1      1     0       0       0       0   

   zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  Embarked  \
0       0  ...        0        0        0       3        0        0       2.0   
1       0  ...        0        0        0       1        0        0       0.0   
2       0  ...        0        0        0       3        0        0       2.0   
3       0  ...        0        0        0       1        0        0       2.0   
4       0  ...        0        0        0       3        0        0       2.0   
5       0  ...        0        0        0       3        0        0       1.0   
6       0  ...        0        0        0       1        0        0       2.0   
7       0  ...        0        0        0       3        0        0       2.0   
8       0  ...        0        0        0       3        0        0       2.0   
9       0  ...        0        0        0       2        0        0       0.0   

   zero.17  zero.18  2urvived  
0        0        0         0  
1        0        0         1  
2        0        0         1  
3        0        0         1  
4        0        0         0  
5        0        0         0  
6        0        0         0  
7        0        0         0  
8        0        0         1  
9        0        0         1  

[10 rows x 28 columns]

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1309 non-null   int64  
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64  
 4   sibsp        1309 non-null   int64  
 5   zero         1309 non-null   int64  
 6   zero.1       1309 non-null   int64  
 7   zero.2       1309 non-null   int64  
 8   zero.3       1309 non-null   int64  
 9   zero.4       1309 non-null   int64  
 10  zero.5       1309 non-null   int64  
 11  zero.6       1309 non-null   int64  
 12  Parch        1309 non-null   int64  
 13  zero.7       1309 non-null   int64  
 14  zero.8       1309 non-null   int64  
 15  zero.9       1309 non-null   int64  
 16  zero.10      1309 non-null   int64  
 17  zero.11      1309 non-null   int64  
 18  zero.12      1309 non-null   int64  
 19  zero.1

In [88]:
age_column = df["Age"]
age_column

0       22.0
1       38.0
2       26.0
3       35.0
4       35.0
        ... 
1304    28.0
1305    39.0
1306    38.5
1307    28.0
1308    28.0
Name: Age, Length: 1309, dtype: float64

In [89]:
df_small = df[["Passengerid", "2urvived", "Age"]]

In [90]:
df_small

Passengerid  2urvived   Age
0               1         0  22.0
1               2         1  38.0
2               3         1  26.0
3               4         1  35.0
4               5         0  35.0
...           ...       ...   ...
1304         1305         0  28.0
1305         1306         0  39.0
1306         1307         0  38.5
1307         1308         0  28.0
1308         1309         0  28.0

[1309 rows x 3 columns]

In [91]:
df.index

RangeIndex(start=0, stop=1309, step=1)

EX3:
load the titanic dataset, calculate the correlations, and print the correlation between the passengerid and 2urvived

In [92]:
df_small.corr()

Passengerid  2urvived       Age
Passengerid     1.000000 -0.331493  0.025799
2urvived       -0.331493  1.000000 -0.055862
Age             0.025799 -0.055862  1.000000

In [93]:
print(f"the correlation between Passengerid and 2survived is {df_small['Passengerid'].corr(df_small['2urvived'])}")

the correlation between Passengerid and 2survived is -0.33149303092420623


In [94]:
corr = df_small.corr()
print(f"the correlation between Passengerid and 2survived is {corr['Passengerid']['2urvived']}")

the correlation between Passengerid and 2survived is -0.331493030924206


In [95]:
res = corr['Passengerid'].iloc[1]
print(res)

-0.331493030924206


In [96]:
df

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0   
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0   
1          0  ...        0        0        0       1        0        0   
2          0  ...        0        0        0       3        0        0   
3          0  ...        0        0        0       1        0        0   
4          0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
0          2.0        0        0         0  
1          0.0        0        0         1  
2          2.0        0        0         1  
3          2.0        0        0         1  
4          2.0        0        0         0  
...        ...      ...      ...       ...  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[1309 rows x 28 columns]

In [97]:
df_small

Passengerid  2urvived   Age
0               1         0  22.0
1               2         1  38.0
2               3         1  26.0
3               4         1  35.0
4               5         0  35.0
...           ...       ...   ...
1304         1305         0  28.0
1305         1306         0  39.0
1306         1307         0  38.5
1307         1308         0  28.0
1308         1309         0  28.0

[1309 rows x 3 columns]

In [98]:
df = df[["Passengerid", "Age",	"Fare",	"Sex",	"sibsp", "2urvived"]] # this will override the df variable

In [99]:
df

Passengerid   Age      Fare  Sex  sibsp  2urvived
0               1  22.0    7.2500    0      1         0
1               2  38.0   71.2833    1      1         1
2               3  26.0    7.9250    1      0         1
3               4  35.0   53.1000    1      1         1
4               5  35.0    8.0500    0      0         0
...           ...   ...       ...  ...    ...       ...
1304         1305  28.0    8.0500    0      0         0
1305         1306  39.0  108.9000    1      0         0
1306         1307  38.5    7.2500    0      0         0
1307         1308  28.0    8.0500    0      0         0
1308         1309  28.0   22.3583    0      1         0

[1309 rows x 6 columns]

In [100]:
df_new = df.rename(columns={"2urvived":"survived"})

In [101]:
df_new

Passengerid   Age      Fare  Sex  sibsp  survived
0               1  22.0    7.2500    0      1         0
1               2  38.0   71.2833    1      1         1
2               3  26.0    7.9250    1      0         1
3               4  35.0   53.1000    1      1         1
4               5  35.0    8.0500    0      0         0
...           ...   ...       ...  ...    ...       ...
1304         1305  28.0    8.0500    0      0         0
1305         1306  39.0  108.9000    1      0         0
1306         1307  38.5    7.2500    0      0         0
1307         1308  28.0    8.0500    0      0         0
1308         1309  28.0   22.3583    0      1         0

[1309 rows x 6 columns]

EX4
Check the correlation between the Fare and the Pclass, and the correlation between survived and Sex. Finally print which is higher



In [102]:
corr = df_new.corr()
corr
corr1 = corr['Fare'].iloc[3]
corr2 = corr['survived'].iloc[4]
max_corr = max(corr1,corr2)
print(f"The correlation between fare and sex is {corr1}, the correlation between survived and sibsp is{corr2} and the feature with the higher correlations are: {max_corr}")

The correlation between fare and sex is 0.18568128646707774, the correlation between survived and sibsp is-0.014375452914690567 and the feature with the higher correlations are: 0.18568128646707774


In [103]:
corr = df_new.corr()
corr1 = corr['Fare']['Sex']
corr2 = corr['survived']['sibsp']
max_corr = max(corr1,corr2)
print(f"The correlation between fare and sex is {corr1}, the correlation between survived and sibsp is{corr2} and the feature with the higher correlations are: {max_corr}")

The correlation between fare and sex is 0.18568128646707774, the correlation between survived and sibsp is-0.014375452914690567 and the feature with the higher correlations are: 0.18568128646707774


# Homework

In this home work you are going to work and learn about numpy and pandas.
If you are met with a function you are not familair with you are expected to search and learn about it your self! Don't worry the internet is full of explanations and tutorials about this packages and you can do it!


## Numpy
Make sure you are testing everything

1. Write a function that gets an argument n, checks if it's higher than 0 and than generates an array in that size of ones.


In [104]:
import numpy as np

def higher_than_0(number):
  if number > 0:
    new_array = np.ones(number, dtype = int)
    return new_array
  else:
    print(f'The number {number} is less or equal to 0')


a = higher_than_0(8)
print(a)

[1 1 1 1 1 1 1 1]


2. Write a function that gets an argument n, checks if it's higher than 0 and than generates an array in that size between 0 to n with step 2.

In [105]:
def higher_than_0(number):
  if number > 0:
    new_array = np.arange(0, number, 2)
    return new_array
  else:
    print(f'The number {number} is less or equal to 0')

higher_than_0(8)

array([0, 2, 4, 6])

3. Write a python function that takes two arrays and calculates their correaltion
hint: Numpy already implemented everything!

In [106]:
def correlation_two_arrays(array1, array2):
  correlation_matrix = np.corrcoef(array1, array2)
  return correlation_matrix

correlation_two_arrays(np.array([1,2,5,6,7,]),np.array([5.2, 6.3, 8.5, 1.3, 9.6]))

array([[1.        , 0.16478989],
       [0.16478989, 1.        ]])

4. Write a python function that takes two arrays and checks if all the elements are equal



In [107]:
def check_if_equal(array1, array2):
  result = np.array_equal(array1, array2)
  return result

check_if_equal(np.array([1,2,3]),np.array([1,2,4]))

False

5. Write a python function that takes two arrays and checks if they contain the same variables not neccesserly in the same order

In [108]:
def contain_same_variables(array1, array2):
  set1 = set(array1)
  set2 = set(array2)
  set1 = sorted(set1)
  set2 = sorted(set2)
  if set1 == set2:
    print('The arrays contains the same variables')
  else:
    print('The arrays does not contain the same variables')

a = np.array([5,6,7,3,4,8])
b = np.array([3,4,5,6,7])
contain_same_variables(a,b)


The arrays does not contain the same variables


# Pandas


In [109]:
df.describe()

Passengerid          Age         Fare          Sex        sibsp  \
count  1309.000000  1309.000000  1309.000000  1309.000000  1309.000000   
mean    655.000000    29.503186    33.281086     0.355997     0.498854   
std     378.020061    12.905241    51.741500     0.478997     1.041658   
min       1.000000     0.170000     0.000000     0.000000     0.000000   
25%     328.000000    22.000000     7.895800     0.000000     0.000000   
50%     655.000000    28.000000    14.454200     0.000000     0.000000   
75%     982.000000    35.000000    31.275000     1.000000     1.000000   
max    1309.000000    80.000000   512.329200     1.000000     8.000000   

          2urvived  
count  1309.000000  
mean      0.261268  
std       0.439494  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000

1. Find the maximum value of each feature

In [110]:
df

Passengerid   Age      Fare  Sex  sibsp  2urvived
0               1  22.0    7.2500    0      1         0
1               2  38.0   71.2833    1      1         1
2               3  26.0    7.9250    1      0         1
3               4  35.0   53.1000    1      1         1
4               5  35.0    8.0500    0      0         0
...           ...   ...       ...  ...    ...       ...
1304         1305  28.0    8.0500    0      0         0
1305         1306  39.0  108.9000    1      0         0
1306         1307  38.5    7.2500    0      0         0
1307         1308  28.0    8.0500    0      0         0
1308         1309  28.0   22.3583    0      1         0

[1309 rows x 6 columns]

In [111]:
max_values = df.max()
print(max_values)

Passengerid    1309.0000
Age              80.0000
Fare            512.3292
Sex               1.0000
sibsp             8.0000
2urvived          1.0000
dtype: float64


2. Filter the table to only the rows where the sex column is 0

In [115]:
filtered_rows_df = df[df['Sex'] == 0]
print(filtered_rows_df)

      Passengerid   Age      Fare  Sex  sibsp  2urvived
0               1  22.0    7.2500    0      1         0
4               5  35.0    8.0500    0      0         0
5               6  28.0    8.4583    0      0         0
6               7  54.0   51.8625    0      0         0
7               8   2.0   21.0750    0      3         0
...           ...   ...       ...  ...    ...       ...
1298         1299  50.0  211.5000    0      1         0
1304         1305  28.0    8.0500    0      0         0
1306         1307  38.5    7.2500    0      0         0
1307         1308  28.0    8.0500    0      0         0
1308         1309  28.0   22.3583    0      1         0

[843 rows x 6 columns]


3. Filter the table to only the rows where Age is above 70

In [116]:
filtered_rows_age_above_70 = df[df['Age'] > 70]
print(filtered_rows_age_above_70)

     Passengerid   Age     Fare  Sex  sibsp  2urvived
96            97  71.0  34.6542    0      0         0
116          117  70.5   7.7500    0      0         0
493          494  71.0  49.5042    0      0         0
630          631  80.0  30.0000    0      0         1
851          852  74.0   7.7750    0      0         0
987          988  76.0  78.8500    1      1         0


4. Filter the table to only the rows where Age is above 70 or below 15

In [121]:
filtered_rows_age_diff_filter = df[(df['Age'] > 70) | (df['Age'] < 15)]
print(filtered_rows_age_diff_filter)

      Passengerid   Age     Fare  Sex  sibsp  2urvived
7               8   2.0  21.0750    0      3         0
9              10  14.0  30.0708    1      1         1
10             11   4.0  16.7000    1      1         1
14             15  14.0   7.8542    1      0         0
16             17   2.0  29.1250    0      4         0
...           ...   ...      ...  ...    ...       ...
1251         1252  14.5  69.5500    0      8         0
1270         1271   5.0  31.3875    0      4         0
1280         1281   6.0  21.0750    0      3         0
1283         1284  13.0  20.2500    0      0         0
1300         1301   3.0  13.7750    1      1         0

[115 rows x 6 columns]


5. Check the precent of the previous group survival rate from the last question and compare it to the entire dataset. Is it better or worse?

survival rate = number of people survived / number of people

In [130]:
survivers_new_df_sum = filtered_rows_age_diff_filter['2urvived'].sum()
survivers_new_df_count = filtered_rows_age_diff_filter['2urvived'].count()
print(survivers_new_df_sum/survivers_new_df_count)

print(filtered_rows_age_diff_filter['2urvived'].mean())
print(df['2urvived'].mean())

0.4
0.4
0.2612681436210848
